#!/bin/sh -f

WS="`pwd`"
test $# -gt 0 && WS="${1:-`pwd`}" && shift
IMAGE=python-ide
#x11docker --podman --xpra --pulseaudio --sudouser --user=RETAIN -- -v "${WS}":/workspace -- "${IMAGE}" "$@"
x11docker --podman --nxagent --user=RETAIN -- --userns=keep-id -v "${WS}":/workspace -- "${IMAGE}" "$@"


