#!/bin/sh -f

WS="`pwd`}"
test $# -gt 0 && WS="${1:-`pwd`}" && shift
IMAGE=python-ide
#x11docker --podman --sudouser --user=RETAIN --xpra --pulseaudio -- -v ${WS}:/workspace -- ${IMAGE}
x11docker --podman --user=RETAIN --nxagent -- -v ${WS}:/workspace -- ${IMAGE} "$@"

